{#
    NOTE: this is a jinja template, rendered in completion_script.rs
#}
# This script was generated by cargo-lab {{version}}. It extends completions
# for the `cargo` command to handle the `cargo lab` subcommand.

# ───── Setup ──────────────────────────────────────────────────── #
_zsh_registered_completion_fn() {
  # Get the completion function registered for a given command, if it exists
  # Prints nothing if it doesn't exist.

  local cmd="$1"
  local registered
  registered=$(echo "$_comps[$cmd]" 2>/dev/null) ||
    return 0
  test -n "$registered" && echo "$registered"
}

# ───── The actual completion function ─────────────────────────────────── #
_CARGO_LAB_PARENT_COMPLETER=$(_zsh_registered_completion_fn "{{cmd}}")

_complete_cargo_lab_combined() {
  if test -n "$_CARGO_LAB_PARENT_COMPLETER"; then
    "$_CARGO_LAB_PARENT_COMPLETER" "$@"
  fi

  _clap_dynamic_completer_{{name}} "$@"
}

# START: script emitted from clap::CompleteEnv
{{clap_completion_script}}
# END: script emitted from clap::CompleteEnv


# ───── Registration ───────────────────────────────────────────── #
# *override* clap script's registration with our "combined" provider
compdef _complete_cargo_lab_combined {{cmd}}
