use crate::cargo_cli_helpers::InvocationType;
use crate::cli;
use crate::config;
use crate::config::Config;
use crate::manifest_editor::CargoDotToml;
use clap::CommandFactory;
use clap_complete::{
    ArgValueCandidates, ArgValueCompleter, CompletionCandidate, PathCompleter,
    Shell, generate,
};
use std::ffi::{OsStr, OsString};
use std::io;
use std::path::Path;

// ───── Dynamic completions ────────────────────────────────────── //
pub fn manifest_path_completer() -> ArgValueCompleter {
    ArgValueCompleter::new(PathCompleter::any().filter(|path: &Path| {
        path.file_name() == Some(OsStr::new("Cargo.toml"))
    }))
}

pub fn script_name_completer() -> ArgValueCandidates {
    ArgValueCandidates::new(|| {
        // TODO: partially parse the current argv (the args after '--')
        //   to see if `--manifest-path` has been passed
        if let Ok(cfg) = Config::from_env(config::Quiet)
            && let Ok(manifest) = CargoDotToml::read(&cfg.cargo_dot_toml)
            && let Some(script_iter) = manifest.list_scripts()
        {
            script_iter
                .map(|script| {
                    CompletionCandidate::new(script.name)
                        .help(Some(script.path.to_string().into()))
                })
                .collect()
        } else {
            vec![]
        }
    })
}

pub fn template_name_completer() -> ArgValueCandidates {
    ArgValueCandidates::new(|| {
        if let Ok(cfg) = Config::from_env(config::Quiet)
            && let Ok(template_iter) = cfg.iter_templates()
        {
            template_iter
                .map(|template| CompletionCandidate::new(template.name))
                .collect()
        } else {
            vec![]
        }
    })
}

// ───── The entrypoint ─────────────────────────────────────────── //
/// "HEY! I'M ~~WALKIN~~ *USING UNSTABLE CLAP_COMPLETE FEATURES* HERE!"
///
/// To use dynamic autocomplete with clap_complete's "unstable_dynamic" feature,
/// this should probably be the very first thing called from main.
/// Things will go very badly for you if there's any STDOUT
/// before this gets called.
///
/// If the `COMPLETE={shell}` env var is *not* set, this is a no-op.
/// Othewrise it acts as the entrypoint for "autocomplete" mode
/// and it will terminate this process upon completion (i.e., the function won't return).
///
/// If the `COMPLETE` env var is set:
/// - if the program is called without any arguments, it outputs the shell
///   completion script to be sourced. This is a completely _different_ script
///   than the one generated by `clap_complete::generate`, which does not include
///   any support for the dynamic options.
/// - The above dynamic completion script includes instructions for the shell
///   to callback with various arguments in order to generate argument lists.
pub fn maybe_exec_dynamic_automcomplete() {
    clap_complete::CompleteEnv::with_factory(cli::PlaygroundCli::command)
        .complete();
}

/// Print the completion script for the requested shell to stdout
/// WARNING: this script only works for *static* completions, the dynamic
/// completions are separate and possibly not even compatible with this
pub fn write_completion_script<Stream>(
    shell: Shell,
    mut dest: Stream,
) -> crate::Result<()>
where
    Stream: io::Write,
{
    let arg_vec: Vec<OsString> = std::env::args_os().collect();
    let invocation_type = InvocationType::from_argv(&arg_vec);

    // the completions we generate depend upon exactly how this is invoked
    let mut cmd = match invocation_type {
        InvocationType::CargoSubcmd(_cargo_path, subcmd_name) => {
            clap::Command::new("cargo").subcommand(
                cli::PlaygroundCli::command() //
                    .name(
                        subcmd_name //
                            .into_string()
                            .unwrap(),
                    ),
            )
        },
        InvocationType::Direct(bin_path) => {
            cli::PlaygroundCli::command() //
                .name(
                    bin_path
                        .file_name()
                        .unwrap()
                        .to_owned()
                        .into_string()
                        .unwrap(),
                )
        },
    };

    let cmd_name = cmd.get_name().to_owned();
    generate(shell, &mut cmd, cmd_name, &mut dest);

    Ok(())
}
